#include <stdint.h>
#include <stdio.h>
#include <string.h>

#ifndef BAREMETAL
#include <sys/mman.h>
#include <stdlib.h>
#include <sys/mman.h>
#endif

#include "include/gemmini_testutils.h"
// #include "include/gemmini_mmio.h"
// HW-layout LUT header generated by lut_mapping_demo.py
#include "include/matmul_fp6_128x128x512.h"
#ifdef MX_ROCKET
#include "include/gemmini_mx_rocket.h"   // standalone: direct RoCC, flat scale window, LUT regmap, spad mvout
#endif

#define TILE 16
#define VALUES_PER_BYTE 2
#define USE_LUT_DEF
#define USE_LUT 1
#define QUANT_LUT_UPDATE_GRANULARITY 1
#define FP6
#define DIM 16

#define ADDR_LEN 32

#define GEMMINI_CTRL 0x40084000
#define GEMMINI_RS1_ADDR (GEMMINI_CTRL + 0x10)
#define GEMMINI_RS2_ADDR (GEMMINI_CTRL + 0x18)
#define GEMMINI_INST_ADDR (GEMMINI_CTRL + 0x0)

// #define GEMMINI_LUT0_ADDR (GEMMINI_CTRL + 0x80)
// #define GEMMINI_LUT1_ADDR (GEMMINI_CTRL + 0x200)
// #define GEMMINI_LUT2_ADDR (GEMMINI_CTRL + 0x380)

#define GEMMINI_LUT0_ADDR (GEMMINI_CTRL + 0x80)  //weight     (64 rows x 96b = 0x300 bytes)
#define GEMMINI_LUT1_ADDR (GEMMINI_CTRL + 0x380) // activation
#define GEMMINI_LUT2_ADDR (GEMMINI_CTRL + 0x680) // output

#define GEMMINI_SF_MEM 0x40088000
#define GEMMINI_SF_MEM_A (GEMMINI_SF_MEM + 0x2000)
#define GEMMINI_SF_MEM_B GEMMINI_SF_MEM
#define SMEM 0x40000000

#define GEMMINI_SPAD_ADDR_A (DIM + MATMUL_N /2 * MATMUL_GK)
#define GEMMINI_SPAD_ADDR_B 0x0
#define GEMMINI_ACC_BASE_ADDR 0x80000000
#define GEMMINI_ACC_ADDR_C GEMMINI_ACC_BASE_ADDR
#define BF16_PER_WORD 4
#define OUT_COLS (MATMUL_M / BF16_PER_WORD)

#define GEMMINI_FORMAT_FP8
#define GEMMINI_FORMAT_FP6
#define GEMMINI_FORMAT_FP4
#undef GEMMINI_BUSY_ADDR
#define GEMMINI_BUSY_ADDR (GEMMINI_CTRL + 0x20)

#if !defined(SPIKE_SIM) && !defined(MX_ROCKET)
#undef gemmini_fence
//#define gemmini_fence() { while (gemmini_status()); }
#define gemmini_fence() { while (*((volatile uint32_t *) GEMMINI_BUSY_ADDR)) asm volatile ("nop"); }
#endif

// TODO: Confirm this enum's values are correct
#ifdef FP8
#define GEMMINI_FORMAT GEMMINI_FORMAT_FP8 0
#else
#ifdef FP6
#define GEMMINI_FORMAT GEMMINI_FORMAT_FP6 1
#else
#define GEMMINI_FORMAT GEMMINI_FORMAT_FP4 2
#endif
#endif

#if !defined(SPIKE_SIM) && !defined(MX_ROCKET)
#undef ROCC_INSTRUCTION_RS1_RS2
#define ROCC_INSTRUCTION_RS1_RS2(x, rs1, rs2, funct) { \
  *((volatile uint64_t *) GEMMINI_RS1_ADDR) = (rs1); \
  *((volatile uint64_t *) GEMMINI_RS2_ADDR) = (rs2); \
  *((volatile uint32_t*) GEMMINI_INST_ADDR) = (0x7B) | (0 << 7) | (3 << 12) | (1 << 15) | (2 << 20) | ((funct) << 25); \
}
#endif

// typedef uint8_t elem_t;
// typedef uint8_t welem_t;
typedef uint8_t out_t;

void load_scale_factors(volatile uint64_t *sf_mem, uint8_t *scale_factors, int n) {
  uint64_t *dword_scale_factors = (uint64_t *) scale_factors;
  for (size_t i = 0; i < n / 8; i ++) {
    sf_mem[i] = dword_scale_factors[i];
  }
}


static inline int popcount8(uint8_t x) {
  int count = 0;
  while (x) {
    count += x & 1;
    x >>= 1;
  }
  return count;
}

int main() {
#ifndef BAREMETAL
  if (mlockall(MCL_CURRENT | MCL_FUTURE) != 0) {
    perror("mlockall");
    return 1;
  }
#endif
  static uint32_t scale_factors[MATMUL_M * MATMUL_N / 32] __attribute__((aligned(32))) = {0};
  static uint64_t C_hw[MATMUL_M][OUT_COLS];
  memset(C_hw, 0, sizeof(C_hw));

  // Configure Gemmini
  gemmini_flush(0);
  // gemmini_config_ex(WEIGHT_STATIONARY, 0, 0); // Full version used instead to configure format
  ROCC_INSTRUCTION_RS1_RS2(XCUSTOM_ACC,
    ((uint64_t)acc_scale_t_to_acc_scale_t_bits((acc_scale_t)ACC_SCALE_IDENTITY) << 32)
    | ((uint64_t)(1) << 16) // A stride
    | (GEMMINI_FORMAT << 14) // C format
    | (GEMMINI_FORMAT << 12) // B format
    | (GEMMINI_FORMAT << 10) // A format
    | (0 << 9) // B transpose
    | (0 << 8) // A transpose
    | ((false) << 7) // Set only strides
    | ((USE_LUT) << 4)
    | ((0) << 3) // Activation function
    | ((WEIGHT_STATIONARY) << 2)
    | CONFIG_EX,
    ((uint64_t)(1) << 48) // C stride
    | (0),
    k_CONFIG);
  int tiles_I = MATMUL_M / 32;                       // = 4
  int tiles_K = MATMUL_K / 16;                         // = 8
  int tiles_J = MATMUL_N / 32 ;                           // = 4  (each n-tile = DIM*2 original cols)
#ifdef MX_ROCKET
  gemmini_config_st(1 * sizeof(uint64_t));   // V1 spad path: match the passing FP4/FP8 requant tests
#else
  gemmini_extended_config_st(DIM * sizeof(out_t), NO_ACTIVATION, 1);
#endif
  // gemmini_extended_mvin((void *) B_in, GEMMINI_SPAD_ADDR_B, MATMUL_N / VALUES_PER_BYTE, MATMUL_K); // TODO: Half one dimension for fp4/6
  //gemmini_mxquant_config_mvout(1024, (uint64_t)scale_factors);
  gemmini_mxquant_config_mvout((uint64_t)scale_factors, tiles_I, tiles_J, tiles_K, 0, 0, QUANT_LUT_UPDATE_GRANULARITY);
  gemmini_extended3_config_ex(WEIGHT_STATIONARY, 0, 0, ACC_SCALE_IDENTITY, 1, 1, 0, 0, false, 1, 1, 1, 1);

   // MVIN B

#ifdef SPIKE_SIM
  gemmini_mx_load_lut((uint64_t)&B_lut[0][0], (MATMUL_N >> QUANT_LUT_UPDATE_GRANULARITY), 0);
  gemmini_mx_load_lut((uint64_t)&A_lut[0][0], (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY), 1);
  gemmini_mx_load_lut((uint64_t)&C_lut[0][0], (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY), 2);
  gemmini_mx_load_scales((uint64_t)&A_scales_row, sizeof(A_scales_row), 0);
  gemmini_mx_load_scales((uint64_t)&B_scales_col, sizeof(B_scales_col), 1);
#elif defined(MX_ROCKET)
  // ISA parity: funct-29 MX_LOAD_LUT DMA loader (same call as SPIKE_SIM), replacing the CPU regmap.
  // sel: 0 = weight(B), 1 = act-in(A), 2 = act-out(C).
  gemmini_mx_load_lut((uint64_t)&B_lut[0][0], (MATMUL_N >> QUANT_LUT_UPDATE_GRANULARITY), 0);
  gemmini_mx_load_lut((uint64_t)&A_lut[0][0], (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY), 1);
  gemmini_mx_load_lut((uint64_t)&C_lut[0][0], (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY), 2);
  gemmini_mx_load_scales((uint64_t)&A_scales_row, sizeof(A_scales_row), 0);
  gemmini_mx_load_scales((uint64_t)&B_scales_col, sizeof(B_scales_col), 1);
  gemmini_fence();
#else
#ifdef USE_LUT_DEF
  for (size_t i = 0; i < (MATMUL_N >> QUANT_LUT_UPDATE_GRANULARITY); i++) {
    volatile uint32_t *dst = ((volatile uint32_t *) GEMMINI_LUT0_ADDR) + 3 * i;
    dst[0] = B_lut[i][0]; dst[1] = B_lut[i][1]; dst[2] = B_lut[i][2];
  }
  for (size_t i = 0; i < (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY); i++) {
    volatile uint32_t *dst = ((volatile uint32_t *) GEMMINI_LUT1_ADDR) + 3 * i;
    dst[0] = A_lut[i][0]; dst[1] = A_lut[i][1]; dst[2] = A_lut[i][2];
  }
  for (size_t i = 0; i < (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY); i++) {
    volatile uint32_t *dst = ((volatile uint32_t *) GEMMINI_LUT2_ADDR) + 3 * i;
    dst[0] = C_lut[i][0]; dst[1] = C_lut[i][1]; dst[2] = C_lut[i][2];
  }
#endif

  load_scale_factors((volatile uint64_t *) GEMMINI_SF_MEM_A, (uint8_t *) &A_scales_row, MATMUL_M*MATMUL_GK);
  load_scale_factors((volatile uint64_t *) GEMMINI_SF_MEM_B, (uint8_t *) &B_scales_col, MATMUL_N*MATMUL_GK);
  gemmini_fence();
#endif
  //gemmini_config_ld(MATMUL_M * sizeof(elem_t));
  // Tile counts
  // A_in_hw[MATMUL_M/2][MATMUL_K]: tiles_I m-tiles x tiles_K k-tiles, each K_TILE hw-rows x DIM bytes
  // B_in[MATMUL_K][MATMUL_N/2]:    tiles_K k-tiles x tiles_J n-tiles, each K_TILE rows x DIM bytes


  uint32_t a_base = 0;
  uint32_t b_base = 8192 - tiles_K * tiles_J * K_TILE;

  // MVIN A: stride = MATMUL_K (full hw-row width); each tile = K_TILE hw-rows x DIM bytes
  gemmini_config_ld((MATMUL_K) * sizeof(uint8_t));
  for (int i = 0; i < tiles_I; i++) {
    for (int k = 0; k < tiles_K; k++) {
      uint8_t *dram_ptr = (uint8_t *)A_in_hw + i * DIM * MATMUL_K + k * DIM;
      uint32_t sp_addr  = a_base + (i * tiles_K + k) * DIM;
      gemmini_extended_mvin((void *) dram_ptr, sp_addr, DIM, DIM);
      gemmini_fence();
    }
  }

  // MVIN B: stride = MATMUL_N/2 (full packed row width); each tile = K_TILE rows x DIM bytes
  gemmini_config_ld((MATMUL_N / VALUES_PER_BYTE) * sizeof(uint8_t));
  for (int k = 0; k < tiles_K; k++) {
    for (int j = 0; j < tiles_J; j++) {
      uint8_t *dram_ptr = (uint8_t *)B_in + k * K_TILE * (MATMUL_N / VALUES_PER_BYTE) + j * DIM;
      uint32_t sp_addr  = b_base + (k * tiles_J + j) * K_TILE;
      gemmini_extended_mvin((void *) dram_ptr, sp_addr, DIM, DIM);
      gemmini_fence();
    }
  }

  int SPAD_DEST = 0;

 uint32_t acc_addr = (1u << (ADDR_LEN - 1));
 gemmini_loop_ws_spad( tiles_I, tiles_J, tiles_K,
      0, 0, 0,              // pad_I=0, pad_J=0, pad_K=0
      a_base,               // A scratchpad address
      8192,                 // B scratchpad end address
      0,                    // D (bias) - none
      SPAD_DEST,   // C accumulator address
      false, false,         // A_transpose, B_transpose
      false, false, false,  // full_C, low_D, ex_accumulate
      NO_ACTIVATION,        // activation
      0, 0,                 // a_spad_id, b_spad_id, double buffer setting
      false,                // is_resadd
      0x38);       //now skip the, ldA, ldB, and st

//   ┌─────┬──────┬────────────────────────────────┐
//   │ Bit │ Mask │             Skips              │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 3   │ 0x08 │ ldA (skip loading A from DRAM) │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 4   │ 0x10 │ ldB (skip loading B from DRAM) │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 5   │ 0x20 │ ldD (skip loading D/bias)      │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 6   │ 0x40 │ ex  (skip compute)             │Z
//   ├─────┼──────┼────────────────────────────────┤
//   │ 7   │ 0x80 │ st (skip acc→spad store)       │
//   └─────┴──────┴────────────────────────────────┘
// gemmini_config_ld(DIM * sizeof(welem_t));
// gemmini_preload(1 * DIM, (1u << (ADDR_LEN - 1)));
// gemmini_config_ld(DIM * sizeof(elem_t));
// gemmini_compute_preloaded(0 * DIM, GARBAGE_ADDR);

        // gemmini_extended4_config_ld(DIM * sizeof(welem_t), MVIN_SCALE_IDENTITY, false, TILE, 0);
        // gemmini_preload(GEMMINI_SPAD_ADDR_B + k, GEMMINI_ACC_ADDR_C + m);
        // gemmini_extended4_config_ld(DIM * sizeof(elem_t), MVIN_SCALE_IDENTITY, false, TILE, 0);
  //       // gemmini_compute_preloaded(GEMMINI_SPAD_ADDR_A + k, k == 0 ? GARBAGE_ADDR : GEMMINI_ACC_ADDR_C);
  //     }
  //   }
  // }

  gemmini_fence();

#ifdef SPIKE_SIM
  // FP6 requant: packed 4-bit C_lut indices, 2 per byte. (M/2)*N bytes = M*N/4 uint16.
  gemmini_mx_read_smem(&C_hw[0][0], SPAD_DEST * 16, MATMUL_M * MATMUL_N / 4);
#elif defined(MX_ROCKET)
  // V1: requant FP6 output in internal spad, mesh-interleaved + row-major-contiguous (Option A).
  // Flat spad->DRAM readback. FP6 packs 2 codes/byte -> M*N/2 bytes -> M*N/2/DIM rows from SPAD_DEST.
  gemmini_fence();
  gemmini_config_st(DIM * sizeof(uint8_t));
  uint8_t *c_base = (uint8_t *) C_hw;
  int total_spad_rows = MATMUL_M * MATMUL_N / 2 / DIM;
  for (int r = 0; r < total_spad_rows; r += DIM) {
    gemmini_extended_mvout(c_base + r * DIM, SPAD_DEST + r, DIM, DIM);
  }
  gemmini_fence();
#else
  uint64_t* smem_start_addr = ((uint64_t*)SMEM) + SPAD_DEST * 2;
  printf("Address: %p \n", smem_start_addr);
  for (int i = 0; i < MATMUL_M/2; i ++) {
    for (int j = 0; j < OUT_COLS; j++) {
        C_hw[i][j] = *(smem_start_addr + (i*OUT_COLS + j));
    }
  }

  gemmini_fence();
#endif

 int errors = 0;
  int diff1 = 0, diff2 = 0, diff3plus = 0;
  int printed = 0;   // cap mismatch prints (baremetal putchar can't take mass output)
  uint8_t *hw_bytes = (uint8_t *)C_hw;

  for (int i = 0; i < MATMUL_M/2; i++) {
    for (int j = 0; j < MATMUL_N; j++) {
      uint8_t got = hw_bytes[i * MATMUL_N + j];
      uint8_t exp = C_proj_hw[i][j];

      // Check low nibble
      uint8_t got_lo = got & 0x0F;
      uint8_t exp_lo = exp & 0x0F;
      if (got_lo != exp_lo) {
        errors++;
        int bits = popcount8(got_lo ^ exp_lo);
        if (printed++ < 40) printf("C_proj_hw[%d][%d]: got: %x, exp: %x \n", i, j, got_lo, exp_lo);
        if      (bits == 1) diff1++;
        else if (bits == 2) diff2++;
        else                diff3plus++;
      }

      // Check high nibble
      uint8_t got_hi = (got >> 4) & 0x0F;
      uint8_t exp_hi = (exp >> 4) & 0x0F;
      if (got_hi != exp_hi) {
        errors++;
        int bits = popcount8(got_hi ^ exp_hi);
        if (printed++ < 40) printf("C_proj_hw[%d][%d]: got: %x, exp: %x \n", i, j, got_hi, exp_hi);
        if      (bits == 1) diff1++;
        else if (bits == 2) diff2++;
        else                diff3plus++;
      }
    }
  }

  if (errors == 0) {
    printf("fp8 WS matmul test PASSED (no mismatches).\n");
  } else {
    printf("fp8 WS matmul test FAILED with %d mismatches.\n", errors);
    printf("  differ by 1 bit:   %d\n", diff1);
    printf("  differ by 2 bits:  %d\n", diff2);
    printf("  differ by 3+ bits: %d\n", diff3plus);
  }


}
