#include <stdint.h>
#include <stdio.h>
#include <string.h>

#ifndef BAREMETAL
#include <sys/mman.h>
#include <stdlib.h>
#include <sys/mman.h>
#endif

#include "include/gemmini_testutils.h"
// #include "include/gemmini_mmio.h"
// HW-layout LUT header generated by lut_mapping_demo.py
#include "include/matmul_data_mx_lut_hw.h"

#define TILE 16
#define VALUES_PER_BYTE 2
#define USE_LUT_DEF
#define USE_LUT 1
#define QUANT_LUT_UPDATE_GRANULARITY 1
#define FP6
#define DIM 16

#define ADDR_LEN 32

#define GEMMINI_CTRL 0x40084000
#define GEMMINI_RS1_ADDR (GEMMINI_CTRL + 0x10)
#define GEMMINI_RS2_ADDR (GEMMINI_CTRL + 0x18)
#define GEMMINI_INST_ADDR (GEMMINI_CTRL + 0x0)

// #define GEMMINI_LUT0_ADDR (GEMMINI_CTRL + 0x80)
// #define GEMMINI_LUT1_ADDR (GEMMINI_CTRL + 0x200)
// #define GEMMINI_LUT2_ADDR (GEMMINI_CTRL + 0x380)

#define GEMMINI_LUT0_ADDR (GEMMINI_CTRL + 0x80)  //weight     (64 rows x 96b = 0x300 bytes)
#define GEMMINI_LUT1_ADDR (GEMMINI_CTRL + 0x380) // activation
#define GEMMINI_LUT2_ADDR (GEMMINI_CTRL + 0x680) // output

#define GEMMINI_SF_MEM 0x40088000
#define GEMMINI_SF_MEM_A (GEMMINI_SF_MEM + 0x2000)
#define GEMMINI_SF_MEM_B GEMMINI_SF_MEM

#define GEMMINI_SPAD_ADDR_A (DIM + MATMUL_N /2 * MATMUL_GK)
#define GEMMINI_SPAD_ADDR_B 0x0
#define GEMMINI_ACC_BASE_ADDR 0x80000000
#define GEMMINI_ACC_ADDR_C GEMMINI_ACC_BASE_ADDR

#define GEMMINI_FORMAT_FP8
#define GEMMINI_FORMAT_FP6
#define GEMMINI_FORMAT_FP4
#undef GEMMINI_BUSY_ADDR
#define GEMMINI_BUSY_ADDR (GEMMINI_CTRL + 0x20)

#undef gemmini_fence
//#define gemmini_fence() { while (gemmini_status()); }
#define gemmini_fence() { while (*((volatile uint32_t *) GEMMINI_BUSY_ADDR)) asm volatile ("nop"); }

// TODO: Confirm this enum's values are correct
#ifdef FP8
#define GEMMINI_FORMAT GEMMINI_FORMAT_FP8 0
#else
#ifdef FP6
#define GEMMINI_FORMAT GEMMINI_FORMAT_FP6 1
#else
#define GEMMINI_FORMAT GEMMINI_FORMAT_FP4 2
#endif
#endif

#undef ROCC_INSTRUCTION_RS1_RS2
#define ROCC_INSTRUCTION_RS1_RS2(x, rs1, rs2, funct) { \
  *((volatile uint64_t *) GEMMINI_RS1_ADDR) = (rs1); \
  *((volatile uint64_t *) GEMMINI_RS2_ADDR) = (rs2); \
  *((volatile uint32_t*) GEMMINI_INST_ADDR) = (0x7B) | (0 << 7) | (3 << 12) | (1 << 15) | (2 << 20) | ((funct) << 25); \
}

// typedef uint8_t elem_t;
// typedef uint8_t welem_t;
typedef uint8_t out_t;

void load_scale_factors(volatile uint64_t *sf_mem, uint8_t *scale_factors, int n) {
  uint64_t *dword_scale_factors = (uint64_t *) scale_factors;
  for (size_t i = 0; i < n / 8; i ++) {
    sf_mem[i] = dword_scale_factors[i];
  }
}

void load_lut(volatile uint32_t *lut_mem, uint8_t *lut) {
  lut_mem[0] = (uint32_t) (lut[0] | (lut[1] << 6) | (lut[2] << 12) | (lut[3] << 18) | (lut[4] << 24) | (lut[5] << 30));
  lut_mem[1] = (uint32_t) ((lut[5] >> 2) | (lut[6] << 4) | (lut[7] << 10) | (lut[8] << 16) | (lut[9] << 22) | (lut[10] << 28));
  lut_mem[2] = (uint32_t) ((lut[10] >> 4) | (lut[11] << 2) | (lut[12] << 8) | (lut[13] << 14) | (lut[14] << 20) | (lut[15] << 26));
}

int main() {
#ifndef BAREMETAL
  if (mlockall(MCL_CURRENT | MCL_FUTURE) != 0) {
    perror("mlockall");
    return 1;
  }
#endif
  static uint32_t scale_factors[MATMUL_M * MATMUL_N / 32] __attribute__((aligned(8))) = {0};


  // Configure Gemmini
  gemmini_flush(0);
  // gemmini_config_ex(WEIGHT_STATIONARY, 0, 0); // Full version used instead to configure format
  ROCC_INSTRUCTION_RS1_RS2(XCUSTOM_ACC,
    ((uint64_t)acc_scale_t_to_acc_scale_t_bits((acc_scale_t)ACC_SCALE_IDENTITY) << 32)
    | ((uint64_t)(1) << 16) // A stride
    | (GEMMINI_FORMAT << 14) // C format
    | (GEMMINI_FORMAT << 12) // B format
    | (GEMMINI_FORMAT << 10) // A format
    | (0 << 9) // B transpose
    | (0 << 8) // A transpose
    | ((false) << 7) // Set only strides
    | ((USE_LUT) << 4)
    | ((0) << 3) // Activation function
    | ((WEIGHT_STATIONARY) << 2)
    | CONFIG_EX,
    ((uint64_t)(1) << 48) // C stride
    | (0),
    k_CONFIG);
  int tiles_I = MATMUL_M / 32;                       // = 4
  int tiles_K = MATMUL_K / 16;                         // = 8
  int tiles_J = MATMUL_N / 32 ;                           // = 4  (each n-tile = DIM*2 original cols)
  gemmini_extended_config_st(DIM * sizeof(out_t), NO_ACTIVATION, 1);
  // gemmini_extended_mvin((void *) B_in, GEMMINI_SPAD_ADDR_B, MATMUL_N / VALUES_PER_BYTE, MATMUL_K); // TODO: Half one dimension for fp4/6
  //gemmini_mxquant_config_mvout(1024, (uint64_t)scale_factors);
  gemmini_mxquant_config_mvout((uint64_t)scale_factors, tiles_I, tiles_J, tiles_K, 0, 0, QUANT_LUT_UPDATE_GRANULARITY);
   // MVIN B
    
#ifdef USE_LUT_DEF
  // A_lut[M>>G][LUT_SIZE] and B_lut[N>>G][LUT_SIZE]: one unique LUT per slot
  for (size_t i = 0; i < (MATMUL_N >> QUANT_LUT_UPDATE_GRANULARITY); i++) {
    load_lut(((volatile uint32_t *) GEMMINI_LUT0_ADDR) + 3 * i, (uint8_t *) B_lut[i]);
  }
  for (size_t i = 0; i < (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY); i++) {
    load_lut(((volatile uint32_t *) GEMMINI_LUT1_ADDR) + 3 * i, (uint8_t *) A_lut[i]);
  }
  for (size_t i = 0; i < (MATMUL_M >> QUANT_LUT_UPDATE_GRANULARITY); i++) {
    load_lut(((volatile uint32_t *) GEMMINI_LUT2_ADDR) + 3 * i, (uint8_t *) C_lut[i]);
  }
#endif

  load_scale_factors((volatile uint64_t *) GEMMINI_SF_MEM_A, (uint8_t *) &A_scales_row, MATMUL_M*MATMUL_GK);
  load_scale_factors((volatile uint64_t *) GEMMINI_SF_MEM_B, (uint8_t *) &B_scales_col, MATMUL_N*MATMUL_GK);
  gemmini_fence(); 
  //gemmini_config_ld(MATMUL_M * sizeof(elem_t));
  // Tile counts
  // A_in_hw[MATMUL_M/2][MATMUL_K]: tiles_I m-tiles x tiles_K k-tiles, each K_TILE hw-rows x DIM bytes
  // B_in[MATMUL_K][MATMUL_N/2]:    tiles_K k-tiles x tiles_J n-tiles, each K_TILE rows x DIM bytes
  

  uint32_t a_base = 0;
  uint32_t b_base = 8192 - tiles_K * tiles_J * K_TILE;
  
  // MVIN A: stride = MATMUL_K (full hw-row width); each tile = K_TILE hw-rows x DIM bytes
  gemmini_config_ld((MATMUL_K) * sizeof(uint8_t));
  for (int i = 0; i < tiles_I; i++) {
    for (int k = 0; k < tiles_K; k++) {
      uint8_t *dram_ptr = (uint8_t *)A_in_hw + i * DIM * MATMUL_K + k * DIM;
      uint32_t sp_addr  = a_base + (i * tiles_K + k) * DIM;
      gemmini_extended_mvin((void *) dram_ptr, sp_addr, DIM, DIM);
      gemmini_fence();
    }
  }

  // MVIN B: stride = MATMUL_N/2 (full packed row width); each tile = K_TILE rows x DIM bytes
  gemmini_config_ld((MATMUL_N / VALUES_PER_BYTE) * sizeof(uint8_t));
  for (int k = 0; k < tiles_K; k++) {
    for (int j = 0; j < tiles_J; j++) {
      uint8_t *dram_ptr = (uint8_t *)B_in + k * K_TILE * (MATMUL_N / VALUES_PER_BYTE) + j * DIM;
      uint32_t sp_addr  = b_base + (k * tiles_J + j) * K_TILE;
      gemmini_extended_mvin((void *) dram_ptr, sp_addr, DIM, DIM);
      gemmini_fence();
    }
  }

 uint32_t acc_addr = (1u << (ADDR_LEN - 1));
 gemmini_loop_ws_spad( tiles_I, tiles_J, tiles_K,            
      0, 0, 0,              // pad_I=0, pad_J=0, pad_K=0
      a_base,               // A scratchpad address
      8192,                 // B scratchpad end address
      0,                    // D (bias) - none
      acc_addr,   // C accumulator address
      false, false,         // A_transpose, B_transpose
      false, false, false,  // full_C, low_D, ex_accumulate
      NO_ACTIVATION,        // activation
      0, 0,                 // a_spad_id, b_spad_id, double buffer setting
      false,                // is_resadd
      0x38);       //now skip the, ldA, ldB, and st

// ┌─────┬──────┬────────────────────────────────┐
//   │ Bit │ Mask │             Skips              │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 3   │ 0x08 │ ldA (skip loading A from DRAM) │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 4   │ 0x10 │ ldB (skip loading B from DRAM) │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 5   │ 0x20 │ ldD (skip loading D/bias)      │
//   ├─────┼──────┼────────────────────────────────┤
//   │ 6   │ 0x40 │ ex  (skip compute)             │Z
//   ├─────┼──────┼────────────────────────────────┤
//   │ 7   │ 0x80 │ st (skip acc→spad store)       │
//   └─────┴──────┴────────────────────────────────┘
// gemmini_config_ld(DIM * sizeof(welem_t));
// gemmini_preload(1 * DIM, (1u << (ADDR_LEN - 1)));
// gemmini_config_ld(DIM * sizeof(elem_t));
// gemmini_compute_preloaded(0 * DIM, GARBAGE_ADDR);

        // gemmini_extended4_config_ld(DIM * sizeof(welem_t), MVIN_SCALE_IDENTITY, false, TILE, 0);
        // gemmini_preload(GEMMINI_SPAD_ADDR_B + k, GEMMINI_ACC_ADDR_C + m);
        // gemmini_extended4_config_ld(DIM * sizeof(elem_t), MVIN_SCALE_IDENTITY, false, TILE, 0);
  //       // gemmini_compute_preloaded(GEMMINI_SPAD_ADDR_A + k, k == 0 ? GARBAGE_ADDR : GEMMINI_ACC_ADDR_C);
  //     }
  //   }
  // }
  
  // MVOUT
  // gemmini_mvout((void *) C_hw, (1u << (ADDR_LEN - 1)));
  //gemmini_mvout_spad(dst_addr, (1u << (ADDR_LEN - 1)))
  gemmini_fence();

  // int errors = 0;
  // for (int m = 0; m < MATMUL_M / VALUES_PER_BYTE; m ++) {
  //   for (int n = 0; n < MATMUL_N; n ++) {
  //     uint64_t got = C_hw[m][n];
  //     // uint64_t exp = (uint64_t) C_out[m][n];
  //     // if (got != exp) {
  //         // errors ++;
  //         // printf("Got: %d    Expected: %d\n", got, exp);
  //     // }
  //   }
  // }
}
